# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: ./build.sh
    - name: Make macOS .app file
      run: ./build-macOS.sh
    - name: Upload Windows GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: Expodify-Windows-x64
        path: bin/gui/win-x64/
    - name: Upload Linux GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: Expodify-Linux-x64
        path: bin/gui/linux-x64
    - name: Upload macOS GUI artifact
      uses: actions/upload-artifact@v4
      with:
        name: Expodify-macOS-arm64
        path: bin/gui/app/
    - name: Upload Windows CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: Expodify-Windows-x64
        path: bin/cli/win-x64/
    - name: Upload Linux CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: Expodify-Linux-x64
        path: bin/cli/linux-x64
    - name: Upload macOS CLI artifact
      uses: actions/upload-artifact@v4
      with:
        name: Expodify-macOS-arm64
        path: bin/cli/osx-arm64/